#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

bun run scripts/db/generate-db-json.ts
npx lint-staged --concurrent false
npx concurrently -g -n "eslint,test:unit,build,web" -c "#341BAB,#A6CC66,#3077C6,#FEDE65" "bun run lint" "bun test unit" "bun run build" "cd web && bun run precommit"
