#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

sh scripts/db/generate-db.sh
npx lint-staged --concurrent false
npx concurrently -g -n "eslint,test:unit,build" -c "#341BAB,#A6CC66,#3077C6" "bun run lint" "bun run test:unit" "bun run build"
bun run markdown-magic
