#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx lint-staged --concurrent false
npx concurrently -g -n "eslint,vitest:unit,build" -c "#341BAB,#A6CC66,#3077C6" "bun run lint" "bun run vitest:unit" "bun run build"
bun run markdown-magic
